### PR TITLE
binary tree

### PR DESCRIPTION
**Pull request by SHOBHA-0502**
I have added all the famous and important binary tree questions with proper solutions which help me in my interview. 
https://github.com/prashantkalokhe/Hactoberfest-2022-New/issues/55

kindly merge it will help others too.

### CODE REVIEW

**Comment by prashantkalokhe** [comment]
Make 3 more Pull request 1 code is ok

**Comment by SHOBHA-0502** [comment]
I have added all questions in a binary tree folder, can you please tell me for what should I make 3 more pull requests?

**Comment by prashantkalokhe** [comment]
To complete your Hacktoberfest you need to make 4 different pull request means 4 times pull request

**Comment by SHOBHA-0502** [comment]
sure, I will 
thanks for guiding 🤗.

**Review by SonuKumar81800 — COMMENTED** [review]
@SHOBHA-0502 good job

**Pull request merged**
