### PR TITLE
Added trees files

### PR DESCRIPTION
**Pull request by chandrabosep**
Hey ✋🏼, I am new to open source contributions
I have added Red Black Tree, vertical Order Traversal and Search in Binary Search Tree CPP file.
Hope you accept my PR

### CODE REVIEW

**Comment by chandrabosep** [comment]
Let me know if you want me to add more
Thank you .

**Comment by prashantkalokhe** [comment]
Add 3 more pull request

**Comment by chandrabosep** [comment]
Do you mean shall I add more files to it in a single PR ?

**Comment by prashantkalokhe** [comment]
1 pr 1 code is ok
But you have to make 4 pr

**Pull request merged**
