### PR TITLE
Added Dynamic Programming codes and Handwritten Notes

### PR DESCRIPTION
**Pull request by smitsekhadiaa**

### CODE REVIEW

**Comment by smitsekhadiaa** [comment]
This PR contains Dynamic Programming codes in cpp , along with handwritten notes

**Comment by prashantkalokhe** [comment]
DP 👑 is here

**Comment by prashantkalokhe** [comment]
DP 👑 is here

**Comment by smitsekhadiaa** [comment]
hey @prashantkalokhe can we still win the prizes if we merge 4 PR's before 31st? 🥲

**Pull request merged**
