### PR TITLE
PR against C++ 

### PR DESCRIPTION
**Pull request by Anshul-9923**
I have added a program showing how to calculate square root of integer in C++ language.

### CODE REVIEW

**Comment by Anshul-9923** [comment]
@prashantkalokhe Please give it a #hacktoberfest tag.

**Comment by Anshul-9923** [comment]
@prashantkalokhe Will this PR be considered as a PR for Hacktoberfest ?

**Comment by prashantkalokhe** [comment]
Yes timeer is on or not in Hacktoberfest website

**Comment by Anshul-9923** [comment]
> Yes timeer is on or not in Hacktoberfest website

Yes it's On.

**Pull request merged**
